// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesMovie.Data;

#nullable disable

namespace RazorPagesMovie.Migrations
{
    [DbContext(typeof(RazorPagesMovieContext))]
    [Migration("20231113151105_New_DataAnnotations")]
    partial class New_DataAnnotations : New_DataAnnotationsBase
    {
        public partial class NewDataAnnotations : Migration
        {
            /// <inheritdoc />
            protected override void Up(MigrationBuilder migrationBuilder)
            {
                migrationBuilder.AlterColumn<string>(
                    name: "Title",
                    table: "Movie",
                    type: "nvarchar(60)",
                    maxLength: 60,
                    nullable: false,
                    oldClrType: typeof(string),
                    oldType: "nvarchar(max)");

                migrationBuilder.AlterColumn<string>(
                    name: "Rating",
                    table: "Movie",
                    type: "nvarchar(5)",
                    maxLength: 5,
                    nullable: false,
                    oldClrType: typeof(string),
                    oldType: "nvarchar(max)");

                migrationBuilder.AlterColumn<string>(
                    name: "Genre",
                    table: "Movie",
                    type: "nvarchar(30)",
                    maxLength: 30,
                    nullable: false,
                    oldClrType: typeof(string),
                    oldType: "nvarchar(max)");
            }
        }
    }
}
